spring.application.name=LostandFound

spring.datasource.url=jdbc:mysql://localhost:3306/LostandFound
spring.datasource.username=root
spring.datasource.password=Pratham@1
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
server.port=8080